### ISSUE TITLE
New Generation WSDL AND SSL

### ISSUE THREAD

**Issue by TomBoehm** [filipp/py-gsxws#4]
Would it be possible to add the new certificate based authentification?
(The modifications from the php project - in issue #42 work perfect.)

**Comment by filipp** [comment]
Working on it. I've made the necessary changes, but there appears to be some issue with the certs I got from Apple so I'm trying to sort this out with them....

**Comment by TomBoehm** [comment]
Hi Filipp

I'd be glad if I can help with the testing. 
My certificate seems to be ok , because it works using the php procect

Best regards 
Tom
——————————————————————————————————

Thomas Böhm

iXpert
Dr.Karl Renner Strasse 15
2650 Payerbach

Tel: +43 680 1455901
Mail: tom@boehm.gl
Web: http://iXpert.at


Von meinem iPhone gesendet.

**Comment by filipp** [comment]
<script src="https://gist.github.com/filipp/0a02edf397b24c0d5d6b.js"></script>

**Comment by filipp** [comment]
Basically, it's this:
https://gist.github.com/filipp/0a02edf397b24c0d5d6b

It requires the "requests" package (pip install requests) Let me know how it goes. Thanks!

**Comment by TomBoehm** [comment]
It seems to work.
I get my userSessionId ...

But we do have some warnings:
/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
<?xml version='1.0' encoding='UTF-8'?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
    <S:Body>
        <ns4:AuthenticateResponse xmlns:ns2="http://asp.core.endpoint.ws.gsx.ist.apple.com/" xmlns:ns3="http://gsxws.apple.com/elements/core/asp" xmlns:ns4="http://gsxws.apple.com/elements/global" xmlns:ns5="http://gsxws.apple.com/elements/core/asp/emea" xmlns:ns6="http://gsxws.apple.com/elements/core">
            <AuthenticateResponse>
                <userSessionId>QXFSLMe7hVos8nAFC9mu</userSessionId>
                <operationId>ufrGaFN4rrHQvFx9BTQzABT</operationId>
            </AuthenticateResponse>
        </ns4:AuthenticateResponse>
    </S:Body>
</S:Envelope>

**Comment by filipp** [comment]
Yup, that warning's a known issue. Good to know the code works - must be something wrong with my account or certs then. I'd really like to get this working on my machine as well before publishing the changes. Thanks for your input - will post back as soon as it's working.

**Comment by TomBoehm** [comment]
I use the certificate unchanged as I got it from Apple,
removed the password from the key
and I am behind the whitelisted IP ...

**Comment by filipp** [comment]
It should be in there now. I decided to set the cert and key paths with environment variables, since they must be sent out with every request. Give it a spin and let me know how it goes! :)

**Comment by TomBoehm** [comment]
Works perfect!
The "InsecurePlatformWarning" is still there, but SSL communication is functional ;-)
great job ! 
thx !!

**Comment by filipp** [comment]
awesome. :) Yeah, that warning might be an OS X-specific thing, but so far I haven't noticed any actual problems with it. Next up - getting all the tests to succeed! :)
